package com.cn.jblog.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("jblog_article_common", "article_Id", ArticleCommon.class);
		arp.addMapping("jblog_article_temp", "temp_Id", ArticleTemp.class);
		arp.addMapping("jblog_articlepm", "p", Articlepm.class);
		arp.addMapping("jblog_user", "user_Id", User.class);
	}
}

