package com.cn.jblog.model;

import com.cn.jblog.model.base.BaseArticleTemp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ArticleTemp extends BaseArticleTemp<ArticleTemp> {
	
}
