package com.cn.jblog.model;

import com.cn.jblog.model.base.BaseArticleCommon;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ArticleCommon extends BaseArticleCommon<ArticleCommon> {
	
}
