package com.cn.jblog.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseArticlepm<M extends BaseArticlepm<M>> extends Model<M> implements IBean {

	public M setP(java.lang.String p) {
		set("p", p);
		return (M)this;
	}
	
	public java.lang.String getP() {
		return getStr("p");
	}

}
