package com.cn.jblog.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public M setUserId(java.lang.String userId) {
		set("user_Id", userId);
		return (M)this;
	}
	
	public java.lang.String getUserId() {
		return getStr("user_Id");
	}

	public M setUserName(java.lang.String userName) {
		set("user_Name", userName);
		return (M)this;
	}
	
	public java.lang.String getUserName() {
		return getStr("user_Name");
	}

	public M setUserPassword(java.lang.String userPassword) {
		set("user_Password", userPassword);
		return (M)this;
	}
	
	public java.lang.String getUserPassword() {
		return getStr("user_Password");
	}

	public M setUserRole(java.lang.String userRole) {
		set("user_Role", userRole);
		return (M)this;
	}
	
	public java.lang.String getUserRole() {
		return getStr("user_Role");
	}

	public M setUserClass(java.lang.String userClass) {
		set("user_Class", userClass);
		return (M)this;
	}
	
	public java.lang.String getUserClass() {
		return getStr("user_Class");
	}

	public M setUserCreateTime(java.util.Date userCreateTime) {
		set("user_Create_Time", userCreateTime);
		return (M)this;
	}
	
	public java.util.Date getUserCreateTime() {
		return get("user_Create_Time");
	}

	public M setUserLoginTime(java.util.Date userLoginTime) {
		set("user_Login_Time", userLoginTime);
		return (M)this;
	}
	
	public java.util.Date getUserLoginTime() {
		return get("user_Login_Time");
	}

	public M setUserCustom(java.lang.String userCustom) {
		set("user_Custom", userCustom);
		return (M)this;
	}
	
	public java.lang.String getUserCustom() {
		return getStr("user_Custom");
	}

}
