package com.cn.jblog.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseArticleTemp<M extends BaseArticleTemp<M>> extends Model<M> implements IBean {

	public M setTempId(java.lang.String tempId) {
		set("temp_Id", tempId);
		return (M)this;
	}
	
	public java.lang.String getTempId() {
		return getStr("temp_Id");
	}

	public M setTempName(java.lang.String tempName) {
		set("temp_Name", tempName);
		return (M)this;
	}
	
	public java.lang.String getTempName() {
		return getStr("temp_Name");
	}

}
