package com.cn.jblog.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseArticleCommon<M extends BaseArticleCommon<M>> extends Model<M> implements IBean {

	public M setArticleId(java.lang.String articleId) {
		set("article_Id", articleId);
		return (M)this;
	}
	
	public java.lang.String getArticleId() {
		return getStr("article_Id");
	}

	public M setArticleName(java.lang.String articleName) {
		set("article_Name", articleName);
		return (M)this;
	}
	
	public java.lang.String getArticleName() {
		return getStr("article_Name");
	}

	public M setArticleTitle(java.lang.String articleTitle) {
		set("article_Title", articleTitle);
		return (M)this;
	}
	
	public java.lang.String getArticleTitle() {
		return getStr("article_Title");
	}

	public M setArticleContent(java.lang.String articleContent) {
		set("article_Content", articleContent);
		return (M)this;
	}
	
	public java.lang.String getArticleContent() {
		return getStr("article_Content");
	}

}
